<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StablishmentSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    DB::table('stablishments')->insert([
      'name'=>'Negocio 1',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Donceles 55.',
      'lat'=>19.69479373372331,
      'lng'=>-99.00168844961155,
      'image'=>'negocio-1-logo.png',
      'summary'=>'negocio-1-summary.png',
      'phone'=>'55 5857-5658',
      'whatsapp'=>'55 5857-5658',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'web'=>'www.google.com',
      'hour'=>'9.00-18.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>1,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>1,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Black Neón',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. reforma x152',
      'lat'=>19.693003001343378,
      'lng'=>-99.00177884773704,
      'image'=>'black_neon-1-logo.png',
      'summary'=>'black_neon-1-summary.png',
      'phone'=>'55 1236-5478',
      'whatsapp'=>'55 1236-5478',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'10.00-16.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>0,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>2,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'La vaca roja',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Juárez  B-152',
      'lat'=>19.69153830254643,
      'lng'=>-99.00181103424912,
      'image'=>'la_vaca_roja-1-logo.png',
      'summary'=>'la_vaca_roja-1-summary.png',
      'phone'=>'55 7744-7788',
      'whatsapp'=>'55 7744-7788',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>1,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>3,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Black and white',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Nápoles B-152',
      'lat'=>19.691422136218204,
      'lng'=>-98.99622667513572,
      'image'=>'black_and_white-1-logo.png',
      'summary'=>'black_and_white-1-summary.png',
      'phone'=>'55 4455-9988',
      'whatsapp'=>'55 4455-9988',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>0,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>4,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Taco',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Iztapalapa C-78',
      'lat'=>19.6886878722868,
      'lng'=>-98.99206928291413,
      'image'=>'taco-1-logo.png',
      'summary'=>'taco-1-summary.png',
      'phone'=>'55 8822-4477',
      'whatsapp'=>'55 8822-4477',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>1,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>5,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'El zig zag',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Iztapalapa C-78',
      'lat'=>19.685773539444885,
      'lng'=>-98.99064303354729,
      'image'=>'el_zig_zag-1-logo.png',
      'summary'=>'el_zig_zag-1-summary.png',
      'phone'=>'55 4411-2222',
      'whatsapp'=>'55 4411-2222',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>0,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>1,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Apple Fit',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Iztapalapa A-12',
      'lat'=>19.691873577404955,
      'lng'=>-98.98546908642777,
      'image'=>'apple_fit-1-logo.png',
      'summary'=>'apple_fit-1-summary.png',
      'phone'=>'55 1111-5566',
      'whatsapp'=>'55 1111-5566',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>1,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>2,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Nike',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Iztapalapa 7-12',
      'lat'=>19.693416407376134,
      'lng'=>-98.9806744609655,
      'image'=>'nike-1-logo.png',
      'summary'=>'nike-1-summary.png',
      'phone'=>'55 7845-1544',
      'whatsapp'=>'55 7845-1544',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>0,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>3,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'El hacha',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Iztapalapa 782',
      'lat'=>19.688730729767663,
      'lng'=>-98.97533361229748,
      'image'=>'el_hacha-1-logo.png',
      'summary'=>'el_hacha-1-summary.png',
      'phone'=>'55 7845-1544',
      'whatsapp'=>'55 7845-1544',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>1,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>4,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Puma',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'direction'=>'C. Iztapalapa 782',
      'lat'=>19.70258819529821,
      'lng'=>-98.97269083839687,
      'image'=>'puma-1-logo.png',
      'summary'=>'puma-1-summary.png',
      'phone'=>'55 7845-1544',
      'whatsapp'=>'55 7845-1544',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>0,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>5,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Alce Negro',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'direction'=>'C. Iztapalapa 2',
      'lat'=>19.7145886418127,
      'lng'=>-98.97349952708176,
      'image'=>'alce_negro-1-logo.png',
      'summary'=>'alce_negro-1-summary.png',
      'phone'=>'55 7845-7788',
      'whatsapp'=>'55 7845-7788',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>1,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>1,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Green Food',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'direction'=>'C. Iztapalapa 2',
      'lat'=>19.676745817410175,
      'lng'=>-98.99588871630286,
      'image'=>'green_food-1-logo.png',
      'summary'=>'green_food-1-summary.png',
      'phone'=>'55 7845-7788',
      'whatsapp'=>'55 7845-7788',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>0,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>2,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Bad H-1',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'direction'=>'C. Iztapalapa 2',
      'lat'=>19.67309579605355,
      'lng'=>-99.00295407094353,
      'image'=>'bad_h1-1-logo.png',
      'summary'=>'bad_h1-1-summary.png',
      'phone'=>'55 7845-7788',
      'whatsapp'=>'55 7845-7788',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>1,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>3,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Barco Azul',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Iztapalapa 452',
      'lat'=>19.684713036624554,
      'lng'=>-99.01678691516108,
      'image'=>'barco_azul-1-logo.png',
      'summary'=>'barco_azul-1-summary.png',
      'phone'=>'55 7845-4411',
      'whatsapp'=>'55 7845-4411',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>0,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>4,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Barco Azul',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Iztapalapa 452',
      'lat'=>19.675600102755265,
      'lng'=>-99.03117930530053,
      'image'=>'barco_azul-1-logo.png',
      'summary'=>'barco_azul-1-summary.png',
      'phone'=>'55 7845-4411',
      'whatsapp'=>'55 7845-4411',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>1,
      'expiration'=>'2021-12-01',
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>5,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);

    DB::table('stablishments')->insert([
      'name'=>'Barco Azul',
      'description'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'description2'=>'Aquí descrición del mapa',
      'direction'=>'C. Iztapalapa 452',
      'lat'=>19.64934000052036,
      'lng'=>-99.0133713397067,
      'image'=>'barco_azul-1-logo.png',
      'summary'=>'barco_azul-1-summary.png',
      'phone'=>'55 7845-4411',
      'whatsapp'=>'55 7845-4411',
      'facebook'=>'www.facebook.com/empresa-1',
      'instagram'=>'www.instagram.com/empresa-1',
      'twitter'=>'www.twitter.com/empresa-1',
      'youtube'=>'www.youtube.com/empresa-1',
      'hour'=>'11.00-17.00',
      'likes'=>0,
      'range'=>0,
      'offer'=>0,
      'municipio_id'=>1,
      'section_id'=>1,
      'zone_id'=>1,
      'deleted'=>0,
      'created_at'=>date('Y-m-d h:i:s'),
      'updated_at'=>date('Y-m-d h:i:s')
    ]);
  }
}
